### PR TITLE
Issue #82: Added beadledom-json-common to beadledom-bom (3.x)

### PR DESCRIPTION
**Pull request by stefanmendoza**
What was changed? Why is this necessary?
----------------------------------------

*Explain the changes included in this request, and the reasons for them.*

Added `beadledom-json-common` to the BOM to allow it's import with the BOM.

How was it tested?
----

*Describe the strategy you used to validate these changes. For example, this should mention if you added unit/integration tests and summarize any manual testing you performed by running your branch locally or in a dev environment.*

No functional changes.

----

*This is bare minimum acceptable testing*

- [ ] `mvn clean install -U`

Reviewers
----

- [ ] [John Leacox](https://github.com/johnlcox)
- [ ] [Sundeep Paruvu](https://github.com/sparuvu)
- [ ] [Nimesh Subramanian](https://github.com/nimeshsubramanian)
- [ ] [Supriya Lal](https://github.com/lal-s)
- [ ] [Brian van de Boogaard](https://github.com/b-boogaard)

### CODE REVIEW

**Comment by stefanmendoza** [comment]
Ran into some issues building 3.x, but I'm assuming that's just because it's under development. The changes are identical to PR #83. The build issue I ran into:

```
[ERROR] ----------------------------------------------------
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.
[ERROR] ----------------------------------------------------
```
```
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.1.0:aggregate (default) on project beadledom-parent: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] 	Failure to find com.cerner.beadledom:beadledom-configuration:jar:3.0-SNAPSHOT in http://repo.typesafe.com/typesafe/releases was cached in the local repository, resolution will not be reattempted until the update interval of typesafe-release has elapsed or updates are forced
[ERROR] 	Failure to find com.cerner.beadledom:beadledom-configuration:jar:3.0-SNAPSHOT in http://repo.typesafe.com/typesafe/releases was cached in the local repository, resolution will not be reattempted until the update interval of typesafe-release has elapsed or updates are forced
[ERROR] 	Failure to find com.cerner.beadledom:beadledom-configuration:jar:3.0-SNAPSHOT in http://repo.typesafe.com/typesafe/releases was cached in the local repository, resolution will not be reattempted until the update interval of typesafe-release has elapsed or updates are forced
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by stefanmendoza** [comment]
^ Must've been a local issue since it succeeded on CI

**Comment by johnlcox** [comment]
For the 3.x PR I might just close it and rebase the 3.x branch off of master after merging your other PR that way 3.x always stays ahead of master until we release 3.0.

**Comment by stefanmendoza** [comment]
Sounds good to me! Thanks! 👍

**Pull request closed without merging**
